### ISSUE TITLE
Crear imagen de Dama beach

### ISSUE THREAD

**Issue by hectorsanchez** [hectorsanchez/acheckersgame#15]
Falta crear la imagen de la dama para el tema beach

**Comment by lucianobaraglia** [comment]
Yo me encargo...
Ésto no tiene algo onda para aceptar el ticket?

**Comment by hectorsanchez** [comment]
Nop..
lucianobarablia ->is Working

**Comment by lucianobaraglia** [comment]
lucianobaraglia -> is Working

**Comment by lucianobaraglia** [comment]
Héctor, Héctor...tengo las imágenes para mandar pero no quiero hacer moco, así que explicáme cómo corno hago un push de mi branch sin destruir todo...
Las imágenes modificadas las tengo en un branch local que se llama "issue.15" y estoy parado ahí.
Ahora..."push..."???

**Comment by hectorsanchez** [comment]
Lo enviaste bien, ya lo merge al master,  gracias!
